# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
