# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='phone',
        ),
    ]
