# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170914_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
