# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170914_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
