# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 13:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20170914_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the                                  format: '+999999999'. Up to 15 digits allowed", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
